export const IMAGE_UPLOAD_START = 'IMAGE_UPLOAD_START';
export const IMAGE_UPLOAD_FINISH = 'IMAGE_UPLOAD_FINISH';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_LOAD = 'IMAGE_LOAD';

export const IMAGE_SAVE = 'IMAGE_SAVE';

export const ADD_GLITCH = 'ADD_GLITCH';

export const OPEN_UI_MODAL = 'OPEN_UI_MODAL';
export const CLOSE_UI_MODAL = 'CLOSE_UI_MODAL';
