export const IMAGE_UPLOAD_START = 'IMAGE_UPLOAD_START';
export const IMAGE_UPLOAD_FINISH = 'IMAGE_UPLOAD_FINISH';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';

export const IMAGE_SAVE = 'IMAGE_SAVE';
export const IMAGE_GLITCH = 'IMAGE_GLITCH';
